### ISSUE TITLE
Benchmark weld enabled dask

### ISSUE THREAD

**Issue by stoneyv** [dask/dask-benchmarks#10]
I want to see if the Stanford weld project will speed up dask like they did with project grizzly for pandas and numpy.  Shoumik Palkar of the weld project said that he is interested in enabling Dask. 

Shoumik Palkar of the Stanford weld project expressed interest in enabling Dask with "weld" as they have done with "grizzly" for pandas and numpy.
https://groups.google.com/forum/#!topic/weld-users/SEC33lLaTG8
https://github.com/weld-project/weld/tree/master/examples/python/grizzly

Only the compiler is implemented in the language rust.  It generates native x86 code using LLVM.
https://groups.google.com/forum/#!topic/weld-users/g4QSbSDf4l0

Weld paper
https://cs.stanford.edu/~matei/papers/2017/cidr_weld.pdf

**Comment by hendrikmakait** [comment]
@stoneyv: Out of curiosity - has there been any progress on a weld-enabled dask and the benchmarks or have you given up on the issue?
