### ISSUE TITLE
Fail CI on failing benchmarks

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-benchmarks#25]
The CI passed for https://github.com/dask/dask-benchmarks/pull/24, despite some benchmarks failing.

**Comment by jrbourbeau** [comment]
One approach (which is taken by pandas) is to log stderr and `grep` for `"failed"`

https://github.com/pandas-dev/pandas/blob/8d5e778dacd244ea302a1e8dcf32f968a024eed2/.github/workflows/ci.yml#L83-L86

It would be nice if there was an option to have `asv` exit with a non-zero status if a benchmark failed, but after a quick look through their docs I did not see reference to such an option

**Comment by jrbourbeau** [comment]
Ah, actually there's a new `--strict` option in master (xref https://github.com/airspeed-velocity/asv/pull/865) that, I think, does exactly what we want!
